### ISSUE TITLE
bug with list_audio_to_process when computing spectros on an existing analysis dataset

### ISSUE THREAD

**Issue by cazaudo** [Project-OSmOSE/datarmor-toolkit#58] opened 2024-10-07 10:03 UTC
when the reshaping has already been done (which prints the message as desired: "It seems these spectrogram parameters are already initialized. If it is an error or you want to rerun the initialization, add the force_init argument."), the attribute of dataset instance `list_audio_to_process` takes the list from the original dataset and NOT from the analysis dataset as desired

my very dirty fix for now :  before calling `generate_spectro` I define this variable as follows

dataset.list_audio_to_process = [os.path.basename(x) for x in glob.glob('/home/datawork-osmose/dataset/boussole_MERMAID_v2/data/audio/60_32000/*wav')]

**Comment by Gautzilla** [comment] 2024-10-14 12:35
I think this issue has been resolved with PR #57.

When you call `generate_spectro`, the spectrogram metadata csv file is now created before the building of the job files:
```py
    dataset.prepare_paths()
    spectrogram_metadata_path = dataset.save_spectro_metadata(False)

    for batch in range(dataset.batch_number):
        ...
```
The path to this metadata csv is passed as an argument to the `qsub_spectrogram_generator_pkg.py` script:

```py
script_args=f"--dataset-path {dataset.path} "
            f"--dataset-sr {dataset.dataset_sr} "
            f"--batch-ind-min {i_min} "
            f"--batch-ind-max {i_max} "
            f"--spectrogram-metadata-path {spectrogram_metadata_path} " # HERE
            f"{'--overwrite ' if overwrite else ''}"
            f"{'--save-for-LTAS ' if save_welch else ''}"
            f"{'--save-matrix ' if save_matrix else ''}",
```
And the `Spectrogram` object in this script is instantiated from the _updated_ metadata csv (line 58):
```py
dataset = Spectrogram.from_csv(dataset_path = args.dataset_path, metadata_csv_path = args.spectrogram_metadata_path)
```

I'll let you confirm that these change solve your issue before closing it!

**Comment by cazaudo** [comment] 2024-11-08 10:43
I have just tested it again and i don't think the problem has been solved because the `batch_size` is derived from `nber_files_to_process` (which is derived from `dataset.list_audio_to_process` , l 215) independently from `spectrogram_metadata_path` which is called too late

so even if the dataset path is modified the number of files to be processed will be equal to the number of original files and not to the number of reshaped ones

quick fix : `dataset.list_audio_to_process` should be redefined based on `dataset.spectro_duration` and `dataset.dataset_sr` somewhere before calling it in `generate_spectro`

**Comment by Gautzilla** [comment] 2024-11-08 11:53
I'm not sure I understand the problem correctly, because I can't reproduce it.

Here's a short example, where I use a small dataset for which I:

- Create an analysis dataset involving a reshaping of the audio files
- Generate spectrograms covering the whole time period of the analysis dataset
- Generate spectrograms with different spectro parameters covering a shorter time period of the analysis dataset
- Generate spectrograms using the shape of the original audio files

> so even if the dataset path is modified 

It seems that our workflows seem to differ here. I think you don't have to change the dataset path:

With the following workflow, everything seems to work as intended:

# Dataset initialization

## Original files: 
 - format: 3600_128000 (duration_sr)
 - datetime_begin : 2023-04-05T14:49:06.000+0000 (first file start)
 - datetime_end : 2023-04-05T18:49:06.000+0000 (last file start + file duration)

## Analysis:
```py
dataset.spectro_duration = 600  # seconds
dataset.dataset_sr = 22_000  # Hz
datetime_begin = "2023-04-05T14:49:06+0000"
datetime_end = "2023-04-05T15:29:06+0000"
```

On dataset.initialize() call, the analysis folder is created as intended:

```
small_dataset
├── data
└── audio
    ├── 600_22000
    │   ├── 2023_04_05_14_49_06.wav
    │   ├── 2023_04_05_14_59_06.wav
    │   ├── 2023_04_05_15_09_06.wav
    │   ├── 2023_04_05_15_19_06.wav
    │   ├── metadata.csv
    │   └── timestamp.csv
    └── 3600_128000
```

# Spectrogram generation:

## First generation : covers the whole duration of the analysis:

```py
dataset.nfft = 1_024
dataset.window_size = 4_096
dataset.overlap = 10
dataset.concat = True

generate_spectro(
    dataset=dataset,
    path_osmose_dataset=path_osmose_dataset,
    write_datasets_csv_for_aplose = write_datasets_csv_for_aplose,
    overwrite=True,
    save_matrix=False,
    save_welch=False,
    datetime_begin=datetime_begin,
    datetime_end=datetime_end,
)
```

## Second generation : Different parameters, and covers a shorter time period:
datetime_begin = "2023-04-05T14:49:00+0000"
datetime_end = "2023-04-05T15:00:00+0000" # changed end datetime
dataset.nfft = 512 # changed nfft
dataset.window_size = 4_096
dataset.overlap = 10
dataset.concat = True

generate_spectro(
    dataset=dataset,
    path_osmose_dataset=path_osmose_dataset,
    write_datasets_csv_for_aplose = write_datasets_csv_for_aplose,
    overwrite=True,
    save_matrix=False,
    save_welch=False,
    datetime_begin=datetime_begin,
    datetime_end=datetime_end,
)

## Third generation : Goes back to the original dataset audio shape:
```py
datetime_begin = "2023-04-05T14:49:00+0000"
datetime_end = "2023-04-05T15:49:00+0000"
dataset.spectro_duration = 3600  # seconds
dataset.dataset_sr = 128_000  # Hz
dataset.nfft = 512

generate_spectro(...)
```

## Output 
The spectrograms are created as intended for the 2 requested generations (the weird names of the spectros in the 3600_128000 just comes from the fact that the original audio files were not renamed):

```
processed
└── spectrogram
    ├── 600_22000
    │   ├── 512_4096_10_linear
    │   │   ├── image
    │   │   │   ├── 2023_04_05_14_49_06_1_0.png
    │   │   │   └── 2023_04_05_14_59_06_1_0.png
    │   │   ├── matrix
    │   │   └── metadata.csv
    │   └── 1024_4096_10_linear
    │       ├── image
    │       │   ├── 2023_04_05_14_49_06_1_0.png
    │       │   ├── 2023_04_05_14_59_06_1_0.png
    │       │   ├── 2023_04_05_15_09_06_1_0.png
    │       │   └── 2023_04_05_15_19_06_1_0.png
    │       ├── matrix
    │       └── metadata.csv
    └── 3600_128000
        └── 512_4096_10_linear
            ├── image
            │   ├── 7189.230405144906_1_0.png
            │   └── 7189.230405154906_1_0.png
            ├── matrix
            └── metadata.csv
```

**Comment by cazaudo** [comment] 2024-11-09 13:34
I have created a test dataset on my side too so you can reproduce the problem , you can use this notebook /home/datawork-osmose/spectrogram_generator_issue58.ipynb  on the dataset CINMS_C_test , using the osmose kernel (btw is it update ? )

actually even starting from scratch , ie with only the folder of original audio files , which is outside the scope of this issue but nevermind ,  the workflow does not behave as expected , s you can see below : 18341 audio file reshaped , but only 855 spectro generated (ie the number of original audio files)


ls /home/datawork-osmose/dataset/DCLDE2015_HF/CINMS_C_test/data/audio/60_32000/*wav | wc -l
18341
ls /home/datawork-osmose/dataset/DCLDE2015_HF/CINMS_C_test/processed/spectrogram/60_32000/1024_1024_0_linear/image/*png | wc -l
855

**Comment by cazaudo** [comment] 2024-11-09 14:39
Note also the bug in the cell  :  monitor_job(dataset)   of this notebook

Also wrong counting of files in progress bar , eg Audio file preparation : ONGOING ( 20331 / 536 )

**Comment by cazaudo** [comment] 2024-11-16 09:38
same bug observed on another dataset , reproduce it with /home/datawork-osmose/bug_repro_spectro_generator.ipynb

datarmor0 dcazau/osmose-toolkit% ls /home/datawork-osmose/dataset/glider_WHOI_2014_we04/data/audio/53_31000/*wav | wc -l
13379

datarmor0 dcazau/osmose-toolkit% ls /home/datawork-osmose/dataset/glider_WHOI_2014_we04/processed/spectrogram/53_31000/1024_1024_0_linear/image/*png | wc -l
6081

**Comment by Gautzilla** [comment] 2024-11-20 10:56
We reshaped your original audio **after removing the four files that weren't sampled at 60 kHz**

We used the same file duration (53s) and a very small sample rate (100 Hz) to speed up the process.

This led to 15131 audio files, which is quite more than the 13379 files contained in your reshaped folder.

After running the patched spectrogram generation, I get the expected number of png files:
```
Audio files:.............15131
Processed files:.........15131
```

**Comment by cazaudo** [comment] 2024-11-28 08:35
ok nice! thank you for inspecting in details , if I understood correctly the problem, it highlights the importance of in-depth inspection of audio metadata prior to any data processing , to be related to your work on class Dataset (old anomaly analysis) ? 

However , did you have time to test your new version on dataset CINMS_C_test ? if not I will test it , but this one does not have differences between audio file metadata so we'll see - I test before closing

**Comment by Gautzilla** [comment] 2024-11-28 08:59
> ok nice! thank you for inspecting in details , if I understood correctly the problem, it highlights the importance of in-depth inspection of audio metadata prior to any data processing , to be related to your work on class Dataset (old anomaly analysis) ?

The weird thing here is that the `file_metadata` displays a sr of 60 kHz for **all files**, so something should have happend during the dataset build.

The Dataset class will have quite a facelift but yeah, I'll put triggers if the dataset contains files of mismatching parameters!


> However , did you have time to test your new version on dataset CINMS_C_test ? if not I will test it , but this one does not have differences between audio file metadata so we'll see - I test before closing

I couldn't because I don't have the permissions to access the folder, but I'll take a look if you change the perms!

**Comment by Gautzilla** [comment] 2024-11-28 09:20
You need to change the permissions of the parent `DCLDE2015_HF` folder too

**Comment by cazaudo** [comment] 2024-11-28 09:54
done

**Closed** 2024-11-29 13:21 UTC
Labels: bug
